=== Marko131/xml_project/data/schema/Scientific_Paper.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified"
    vc:minVersion="1.0" vc:maxVersion="1.1"
    xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/">

    <xs:element name="paper">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paper_title">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute fixed="pred:title" name="property" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="author" type="t_author"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="abstract">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="1" name="keywords">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element maxOccurs="unbounded" name="keyword">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                  <xs:extension base="xs:string">
                                                  <xs:attribute name="property" fixed="pred:keyword"
                                                  type="xs:string"/>
                                                  </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element maxOccurs="unbounded" name="abstract_element">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="title" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="quote" type="t_quote"/>
                <xs:element maxOccurs="unbounded" name="section" type="t_section"/>
                <xs:element name="references">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="reference" type="t_reference"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="corresponding_authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" minOccurs="1"
                                name="corresponding_author" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="citations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="citation" type="t_citation"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="date_received" type="xs:date"/>
            <xs:attribute name="date_revised" type="xs:date"/>
            <xs:attribute name="date_accepted" type="xs:date"/>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="t_author">
        <xs:sequence>
            <xs:element name="name">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute fixed="pred:name" form="unqualified" name="property"
                                type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="university">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute fixed="pred:works" name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="1" name="city">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute fixed="pred:city" name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element minOccurs="0" name="state">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute fixed="pred:state" name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="country">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute fixed="pred:country" name="property" type="xs:string"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="about"/>
    </xs:complexType>
    <xs:complexType name="t_section">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="paragraph" type="t_paragraph"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="section" type="t_section"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="box" type="t_box"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="quote" type="t_quote"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="t_quote">
        <xs:sequence>
            <xs:element name="quote_text" type="xs:string"/>
            <xs:element name="source">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="source_author" type="xs:string"/>
                        <xs:element minOccurs="0" name="source_title" type="xs:string"/>
                        <xs:element minOccurs="0" name="source_page" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="about" type="xs:string"/>
        <xs:attribute fixed="pred:referenceOf" name="rel" type="xs:string"/>
        <xs:attribute name="href" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="t_ref">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="id" type="xs:positiveInteger"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="t_reference">
        <xs:sequence>
            <xs:element name="authors" type="xs:string"/>
            <xs:element name="year" type="xs:positiveInteger"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="pages" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:positiveInteger"/>
    </xs:complexType>
    <xs:complexType name="t_image">
        <xs:simpleContent>
            <xs:extension base="xs:base64Binary">
                <xs:attribute name="title" type="xs:string"/>
                <xs:attribute name="description" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="t_link" mixed="true">
        <xs:choice>
            <xs:element name="image" type="t_image"/>
            <xs:element name="text" type="xs:string"/>
        </xs:choice>
        <xs:attribute name="href" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="t_box">
        <xs:sequence>
            <xs:element maxOccurs="1" minOccurs="1" name="image" type="t_image"/>
            <xs:element maxOccurs="1" minOccurs="1" name="textbox" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="title" type="xs:string"/>
        <xs:attribute name="description" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="t_citation">
        <xs:sequence>
            <xs:element name="authors" type="xs:string"/>
            <xs:element name="year" type="xs:positiveInteger"/>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="magazine" type="xs:string"/>
            <xs:element maxOccurs="3" minOccurs="3" name="link" type="t_link"/>
        </xs:sequence>
        <xs:attribute name="number" type="xs:positiveInteger"/>
    </xs:complexType>
    <xs:complexType name="t_paragraph" mixed="true">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="ref" type="t_ref"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="list" type="t_list"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="image" type="t_image"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="link" type="t_link"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="quote" type="t_quote"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="t_list">
        <xs:sequence>
            <xs:element maxOccurs="unbounded" name="item" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Marko131/xml_project/data/instance3.xml
<?xml version="1.0" encoding="UTF-8"?>
<paper xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
 xmlns:pred="http://www.ftn.uns.ac.rs/rdf/examples/predicate/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Marko/Desktop/TEMP/xml_project/data/schema/Scientific_Paper.xsd" date_received="2006-05-04" date_revised="2006-05-04" date_accepted="2006-05-04">
    <status>
        <waiting>waiting</waiting>
    </status>
    <paper_title property="pred:title">paper_title0</paper_title>
    <authors>
        <author about="about0">
            <name property="pred:name">name0</name>
            <university property="pred:works">university0</university>
            <city property="pred:city">city0</city>
            <state property="pred:state">state0</state>
            <country property="pred:country">country0</country>
        </author>
        <author about="about1">
            <name property="pred:name">name1</name>
            <university property="pred:works">university1</university>
            <city property="pred:city">city1</city>
            <state property="pred:state">state1</state>
            <country property="pred:country">country1</country>
        </author>
    </authors>
    <abstract>
        <keywords>
            <keyword property="pred:keyword">keyword0</keyword>
            <keyword property="pred:keyword">keyword1</keyword>
        </keywords>
        <abstract_element title="title0">abstract_element0</abstract_element>
        <abstract_element title="title1">abstract_element1</abstract_element>
    </abstract>
    <quote about="about2" rel="pred:referenceOf" href="href0">
        <quote_text>quote_text0</quote_text>
        <source>
            <source_author>source_author0</source_author>
            <source_title>source_title0</source_title>
            <source_page>source_page0</source_page>
        </source>
    </quote>
    <quote about="about3" rel="pred:referenceOf" href="href1">
        <quote_text>quote_text1</quote_text>
        <source>
            <source_author>source_author1</source_author>
            <source_title>source_title1</source_title>
            <source_page>source_page1</source_page>
        </source>
    </quote>
    <section title="title2">
        <paragraph>
            <ref id="50">ref0</ref>
            <ref id="50">ref1</ref>
            <list>
                <item>item0</item>
                <item>item1</item>
            </list>
            <list>
                <item>item2</item>
                <item>item3</item>
            </list>
            <image title="title3" description="description0">ZGVmYXVsdA==</image>
            <image title="title4" description="description1">ZGVmYXVsdA==</image>
            <link href="href2">
                <text>text0</text>
            </link>
            <link href="href3">
                <text>text1</text>
            </link>
            <quote about="about4" rel="pred:referenceOf" href="href4">
                <quote_text>quote_text2</quote_text>
                <source>
                    <source_author>source_author2</source_author>
                    <source_title>source_title2</source_title>
                    <source_page>source_page2</source_page>
                </source>
            </quote>
            <quote about="about5" rel="pred:referenceOf" href="href5">
                <quote_text>quote_text3</quote_text>
                <source>
                    <source_author>source_author3</source_author>
                    <source_title>source_title3</source_title>
                    <source_page>source_page3</source_page>
                </source>
            </quote>
            <text>text2</text>
            <annotations>
                <annotation>annotation0</annotation>
                <annotation>annotation1</annotation>
            </annotations>
        </paragraph>
        <paragraph>
            <ref id="50">ref2</ref>
            <ref id="50">ref3</ref>
            <list>
                <item>item4</item>
                <item>item5</item>
            </list>
            <list>
                <item>item6</item>
                <item>item7</item>
            </list>
            <image title="title5" description="description2">ZGVmYXVsdA==</image>
            <image title="title6" description="description3">ZGVmYXVsdA==</image>
            <link href="href6">
                <text>text3</text>
            </link>
            <link href="href7">
                <image title="title7" description="description4">ZGVmYXVsdA==</image>
            </link>
            <quote about="about6" rel="pred:referenceOf" href="href8">
                <quote_text>quote_text4</quote_text>
                <source>
                    <source_author>source_author4</source_author>
                    <source_title>source_title4</source_title>
                    <source_page>source_page4</source_page>
                </source>
            </quote>
            <quote about="about7" rel="pred:referenceOf" href="href9">
                <quote_text>quote_text5</quote_text>
                <source>
                    <source_author>source_author5</source_author>
                    <source_title>source_title5</source_title>
                    <source_page>source_page5</source_page>
                </source>
            </quote>
            <text>text4</text>
            <annotations>
                <annotation>annotation2</annotation>
                <annotation>annotation3</annotation>
            </annotations>
        </paragraph>
        <section title="title8">
            <paragraph>
                <ref id="50">ref4</ref>
                <ref id="50">ref5</ref>
                <list>
                    <item>item8</item>
                    <item>item9</item>
                </list>
                <list>
                    <item>item10</item>
                    <item>item11</item>
                </list>
                <image title="title9" description="description5">ZGVmYXVsdA==</image>
                <image title="title10" description="description6">ZGVmYXVsdA==</image>
                <link href="href10">
                    <image title="title11" description="description7">ZGVmYXVsdA==</image>
                </link>
                <link href="href11">
                    <image title="title12" description="description8">ZGVmYXVsdA==</image>
                </link>
                <quote about="about8" rel="pred:referenceOf" href="href12">
                    <quote_text>quote_text6</quote_text>
                    <source>
                    </source>
                </quote>
                <quote about="about9" rel="pred:referenceOf" href="href13">
                    <quote_text>quote_text7</quote_text>
                    <source>
                    </source>
                </quote>
                <text>text5</text>
                <annotations>
                    <annotation>annotation4</annotation>
                    <annotation>annotation5</annotation>
                </annotations>
            </paragraph>
            <paragraph>
                <ref id="50">ref6</ref>
                <ref id="50">ref7</ref>
                <list>
                    <item>item12</item>
                    <item>item13</item>
                </list>
                <list>
                    <item>item14</item>
                    <item>item15</item>
                </list>
                <image title="title13" description="description9">ZGVmYXVsdA==</image>
                <image title="title14" description="description10">ZGVmYXVsdA==</image>
                <link href="href14">
                    <image title="title15" description="description11">ZGVmYXVsdA==</image>
                </link>
                <link href="href15">
                    <image title="title16" description="description12">ZGVmYXVsdA==</image>
                </link>
                <quote about="about10" rel="pred:referenceOf" href="href16">
                    <quote_text>quote_text8</quote_text>
                    <source>
                    </source>
                </quote>
                <quote about="about11" rel="pred:referenceOf" href="href17">
                    <quote_text>quote_text9</quote_text>
                    <source>
                    </source>
                </quote>
                <text>text6</text>
                <annotations>
                    <annotation>annotation6</annotation>
                    <annotation>annotation7</annotation>
                </annotations>
            </paragraph>
            <box title="title17" description="description13">
                <image title="title18" description="description14">ZGVmYXVsdA==</image>
                <textbox>textbox0</textbox>
            </box>
            <box title="title19" description="description15">
                <image title="title20" description="description16">ZGVmYXVsdA==</image>
                <textbox>textbox1</textbox>
            </box>
            <quote about="about12" rel="pred:referenceOf" href="href18">
                <quote_text>quote_text10</quote_text>
                <source>
                    <source_author>source_author6</source_author>
                    <source_title>source_title6</source_title>
                    <source_page>source_page6</source_page>
                </source>
            </quote>
            <quote about="about13" rel="pred:referenceOf" href="href19">
                <quote_text>quote_text11</quote_text>
                <source>
                    <source_author>source_author7</source_author>
                    <source_title>source_title7</source_title>
                    <source_page>source_page7</source_page>
                </source>
            </quote>
        </section>
        <section title="title21">
            <paragraph>
                <ref id="50">ref8</ref>
                <ref id="50">ref9</ref>
