=== Marko131/xml_project/data/Cover_Letter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="cover_letter">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sender" type="t_person"/>
                <xs:element name="receiver" type="t_person"/>
                <xs:element name="paragraphs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="paragraph" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="signature" type="xs:base64Binary"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="t_person">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
            <xs:element name="phone_number" type="xs:string"/>
            <xs:element name="institution" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Marko131/xml_project/backend/data/cover_letter1.xml
<?xml version="1.0" encoding="UTF-8"?>
<cover_letter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Strahinja/Desktop/xml_project/data/schema/Cover_Letter.xsd">
    <sender>
        <name>Petar Petrovic</name>
        <email>email0</email>
        <phone_number>phone_number0</phone_number>
        <institution>institution0</institution>
        <address>address0</address>
    </sender>
    <receiver>
        <name>name1</name>
        <email>email1</email>
        <phone_number>phone_number1</phone_number>
        <institution>institution1</institution>
        <address>address1</address>
    </receiver>
    <paragraphs>
        <paragraph>paragraph0</paragraph>
        <paragraph>paragraph1</paragraph>
    </paragraphs>
    <signature>ZGVmYXVsdA==</signature>
</cover_letter>
