=== Marko131/xml_project/backend/data/schema/Review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="review">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paper_title" type="xs:string"/>
                <xs:element name="reviewer" type="t_reviewer"/>
                <xs:element name="paragraphs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="paragraph" type="t_paragraph"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="t_reviewer">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="working_title" type="xs:string"/>
            <xs:element name="faculty" type="xs:string"/>
            <xs:element name="university" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="t_paragraph">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="text" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Marko131/xml_project/backend/data/review1.xml
<?xml version="1.0" encoding="UTF-8"?>
<review xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/Strahinja/Desktop/xml_project/data/schema/Review.xsd">
    <paper_title>paper_title2</paper_title>
    <reviewer>
        <name>name0</name>
        <working_title>working_title0</working_title>
        <faculty>faculty0</faculty>
        <university>university0</university>
    </reviewer>
    <paragraphs>
        <paragraph>
            <title>title0</title>
            <text>text0</text>
        </paragraph>
        <paragraph>
            <title>title1</title>
            <text>text1</text>
        </paragraph>
    </paragraphs>
</review>
